---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/JobCheckConnectionConfig.yaml
title: JobCheckConnectionConfig
description: job check connection config
type: object
additionalProperties: false
required:
  - connectionConfiguration
  - dockerImage
properties:
  connectionConfiguration:
    description: Integration specific blob. Must be a valid JSON string.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
  spec:
    description: Integration spec. Must be a valid JSON schema.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
  workspaceId:
    type: string
    format: uuid
  dockerImage:
    type: string
